pyxis_url: https://pyxis.dev.engineering.redhat.com/v1
pyxis_cert: RH-IT-Root-CA.crt
icons_dir: ${OUTPUT_DIR:out}/icons/
icons_uri: https://flatpaks.local.fishsoup.net.com/app-icons/
daemon:
        update_interval: 1800
indexes:
        all:
                output: ${OUTPUT_DIR:out}/index/flatpak.json
                registry: registry.access.redhat.com
                tag: latest
                extract_icons: True
        amd64:
                output: ${OUTPUT_DIR:out}/index/flatpak-amd64.json
                architecture: amd64
                tag: latest
                registry: registry.access.redhat.com
                extract_icons: True
registries:
        registry.access.redhat.com:
                public_url: 'https://registry.access.redhat.com/v2/'
                repositories:
                - ubi8
