pyxis_url: https://pyxis.dev.engineering.redhat.com/v1
icons_dir: out/icons/
icons_uri: https://flatpaks.local.fishsoup.net.com/app-icons/
daemon:
        update_interval: 3
indexes:
        all:
                output: out/index/flatpak.json
                registry: registry.access.redhat.com
                tag: latest
                extract_icons: True
        amd64:
                output: out/index/flatpak-amd64.json
                architecture: amd64
                tag: latest
                registry: registry.access.redhat.com
                extract_icons: True
registries:
        registry.access.redhat.com:
                public_url: 'https://registry.access.redhat.com/v2/'
                repositories:
                - ubi8
