pyxis_url: https://catalog.redhat.com/api/containers/v1
# pyxis_url: https://pyxis.dev.engineering.redhat.com/v1
# if missing, system trust root is used; if relative, looked up in included certs
# pyxis_cert: RH-IT-Root-CA.crt
# When extract_icons is set for an index, icons are saved to icons_dir and labels are
# rewritten in the index from a data: URL to an URL formed from icons_uri
icons_dir: ${OUTPUT_DIR:out}/icons/
icons_uri: https://flatpaks.local.fishsoup.net.com/app-icons/
daemon:
        # How often to query Pyxis
        update_interval: 1800
registries:
        # key must match registry ID in Pyxis
        registry.access.redhat.com:
                # Written into the index
                public_url: https://registry.access.redhat.com/
                repositories:
                - ubi8
indexes:
        all:
                # path to the output location - environment variable substitions
                # are possible for all strings
                output: ${OUTPUT_DIR:out}/test/flatpak.json
                registry: registry.access.redhat.com
                tag: latest
                extract_icons: True
        amd64:
                output: ${OUTPUT_DIR:out}/test/flatpak-amd64.json
                architecture: amd64
                tag: latest
                registry: registry.access.redhat.com
                extract_icons: True
