#pyxis_url: https://catalog.redhat.com/api/containers/v1
pyxis_url: https://pyxis.engineering.redhat.com/v1
# if missing, system trust root is used; if relative, looked up in included certs
pyxis_cert: RH-IT-Root-CA.crt
# these define a client certificate/key pair to authenticate to pyxis; this
# shows environment variable substitution with a fallback
pyxis_client_cert: ${PYXIS_CERT_DIR:${HOME}/.config/flatpak-indexer}/client.crt
pyxis_client_key: ${PYXIS_CERT_DIR:${HOME}/.config/flatpak-indexer}/client.key
# When extract_icons is set for an index, icons are saved to icons_dir and labels are
# rewritten in the index from a data: URL to an URL formed from icons_uri
icons_dir: ${OUTPUT_DIR:out}/icons/
icons_uri: https://flatpaks.local.fishsoup.net.com/app-icons/
daemon:
        # How often to query Pyxis
        update_interval: 1800
registries:
        # key must match registry ID in Pyxis
        registry.access.redhat.com:
                # Written into the index
                public_url: https://registry.access.redhat.com/
                # repositories: ['repo1', 'repo2'] overrides querying Pyxis for the list
        # You can also define a pseudo-registry based on koji/brew builds
        brew:
                # internal registry where builds are pushed
                public_url: https://registry-proxy.engineering.redhat.com/
                # name of a Koji config section
                koji_config: brew
indexes:
        all:
                # path to the output location - environment variable substitions
                # are possible for all strings
                output: ${OUTPUT_DIR:out}/test/flatpak-latest.json
                registry: registry.access.redhat.com
                tag: latest
                extract_icons: True
        amd64:
                output: ${OUTPUT_DIR:out}/test/flatpak-latest-amd64.json
                registry: registry.access.redhat.com
                architecture: amd64
                tag: latest
                extract_icons: True
        # These indexes index all Flatpaks found in the rhel-8.2.0-gate tag
        brew:
                output: ${OUTPUT_DIR:out}/brew/flatpak-rhel-8.2.0-gate.json
                registry: brew
                koji_tag: rhel-8.2.0-gate
                extract_icons: True
        brew-amd64:
                output: ${OUTPUT_DIR:out}/brew/flatpak-rhel-8.2.0-gate-amd64.json
                registry: brew
                architecture: amd64
                koji_tag: rhel-8.2.0-gate
                extract_icons: True
